service: api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Resource: "arn:aws:sns:ap-northeast-2:*:api"
      Action:
        - sns:*
    - Effect: Allow
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:table/*"
      Action:
        - dynamodb:*

plugins:
  - serverless-offline

functions:
  rss:
    handler: apis.rss
    events:
      - http: GET rss/{provider}
      - http: GET rss/{provider}/{args+}
  auth-proxy:
    handler: apis.gfw_proxy
    events:
      - http:
          method: ANY
          path: public/proxy/{service}/{provider}
          cors: true
      - http:
          method: ANY
          path: public/proxy/{service}/{provider}/{args+}
          cors: true
      - http:
          method: ANY
          path: proxy/{service}/{provider}
          cors: true
      - http:
          method: ANY
          path: proxy/{service}/{provider}/{args+}
          cors: true
  toby-proxy:
    handler: apis.toby_proxy
    events:
      - http:
          method: ANY
          path: toby/{proxy+}
          cors: true
  notify:
    handler: apis.notify
    events:
      - http: ANY notify/{service}
      - http: ANY notify/{service}/{to}
  wechat:
    handler: apis.wechat
    events:
      - http: POST wechat/auth
      - http: GET wechat/user/{openid}
      - http: POST wechat/user/{openid}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: openid
            AttributeType: S
        KeySchema:
          - AttributeName: openid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
