service: api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2
  timeout: 300

plugins:
  - serverless-offline

functions:
  rss:
    handler: apis.rss
    events:
      - http: GET rss/{provider}
      - http: GET rss/{provider}/{args+}
  auth-proxy:
    handler: apis.gfw_proxy
    events:
      - http:
          method: ANY
          path: proxy/{service}/{provider}
          cors: true
      - http:
          method: ANY
          path: proxy/{service}/{provider}/{args+}
          cors: true
  toby-proxy:
    handler: apis.toby_proxy
    events:
      - http:
          method: ANY
          path: toby/{proxy+}
          cors: true
