service: api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-northeast-2
  timeout: 300

plugins:
  - serverless-offline

functions:
  rss:
    handler: apis.rss_xitu
    events:
      - http: GET rss/xitu
      - http: GET rss/xitu/{category}
  toby-proxy:
    handler: apis.toby_proxy
    events:
      - http:
          method: GET
          path: toby/{proxy+}
          cors: true
      - http:
          method: POST
          path: toby/{proxy+}
          cors: true
